sudo: required
services:
  - docker

before_install:
  - docker build -t bhoopendra/react-test -f ./complex/client/Dockerfile.dev ./complex/client

script:
  - docker run bhoopendra/react-test npm test -- --coverage

after_success:
  - docker build -t bhoopendra/multi-client ./complex/client
  - docker build -t bhoopendra/multi-nginx ./complex/nginx
  - docker build -t bhoopendra/multi-worker ./complex/worker
  - docker build -t bhoopendra/multi-server ./complex/server
  #Login to the Docker Cli
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
  #Push the images to hub.docker.com
  - docker push bhoopendra/multi-client
  - docker push bhoopendra/multi-nginx
  - docker push bhoopendra/multi-worker
  - docker push bhoopendra/multi-server

  # Pull the images from hub.docker.com and deploy to AWS elastic beanstalk
  deploy:
    provider: elasticbeanstalk
    region: us-west-1
    app: muti-docker
    env: MultiDocker-env
    bucket_name: elastibeanstalk.us-west-1.012357
    bucket_path: docker-multi
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
      secure: $AWS_SECRET_KEY